env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  tsconfigRootDir: .
plugins:
  - '@typescript-eslint'
  - import
  - prettier
rules:
  eqeqeq: error
  "import/no-unresolved": "error"
  "@typescript-eslint/no-non-null-assertion": "off"
settings:
  "import/parsers": 
    "@typescript-eslint/parser": [".ts", ".tsx"]
  "import/resolver":
    typescript: {}
      
